In [25]:
import numpy as np
import pandas as pd

### Exercise 1: Create Two numpy array of size 3 X 2 and 2 X 3

In [26]:
arr1 = np.empty(shape = (3,2))
arr2 = np.empty(shape = (2,3))

In [27]:
print(arr1)
print(arr2)

[[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]
[[4.68167805e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


### Exercise 2: Randomly Initalize that array

In [28]:
arr = np.array(list(range(1,7)))
arr1 = arr.reshape(3,2)
arr2 = arr.reshape(2,3)

In [29]:
print("Array 1:\n",arr1)

Array 1:
 [[1 2]
 [3 4]
 [5 6]]


In [30]:
print("Array 2:\n",arr2)

Array 2:
 [[1 2 3]
 [4 5 6]]


### Exercise 3: Perform matrix multiplication

In [31]:
matrix_mul_result = np.dot(arr1, arr2)
matrix_mul_result

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

### Exercise 4: Perform elementwise matrix multiplication

In [32]:
element_wise_mul_result_1 = arr1 * arr2.T
element_wise_mul_result_2 = arr1.T * arr2
print(element_wise_mul_result_1, "\n\n", element_wise_mul_result_2)

[[ 1  8]
 [ 6 20]
 [15 36]] 

 [[ 1  6 15]
 [ 8 20 36]]


### Exercise 5: Find mean of first matrix

In [33]:
mean_arr1 = np.mean(arr1)
print(mean_arr1)

3.5


### Exercise 6: Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version

In [34]:
data = pd.read_csv(r"mtcars.csv")
print(data.shape)
data.head()

(32, 12)


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [35]:
def centered_mean(column):
    arr = np.array(column)
    arr = arr - np.mean(arr)
    return pd.DataFrame(arr)

In [36]:
data_columns = data.columns
for i in range(1,12):
    data[data_columns[i]] = centered_mean(data[data_columns[i]])

In [37]:
data.head()

Unnamed: 0       mpg     cyl        disp       hp      drat  \
0          Mazda RX4  0.909375 -0.1875  -70.721875 -36.6875  0.303437   
1      Mazda RX4 Wag  0.909375 -0.1875  -70.721875 -36.6875  0.303437   
2         Datsun 710  2.709375 -2.1875 -122.721875 -53.6875  0.253437   
3     Hornet 4 Drive  1.309375 -0.1875   27.278125 -36.6875 -0.516563   
4  Hornet Sportabout -1.390625  1.8125  129.278125  28.3125 -0.446563   

        wt     qsec      vs       am    gear    carb  
0 -0.59725 -1.38875 -0.4375  0.59375  0.3125  1.1875  
1 -0.34225 -0.82875 -0.4375  0.59375  0.3125  1.1875  
2 -0.89725  0.76125  0.5625  0.59375  0.3125 -1.8125  
3 -0.00225  1.59125  0.5625 -0.40625 -0.6875 -1.8125  
4  0.22275 -0.82875 -0.4375 -0.40625 -0.6875 -0.8125

In [38]:
data.sample()

Unnamed: 0       mpg     cyl        disp       hp      drat       wt  \
31  Volvo 142E  1.309375 -2.1875 -109.721875 -37.6875  0.513438 -0.43725   

       qsec      vs       am    gear    carb  
31  0.75125  0.5625  0.59375  0.3125 -0.8125