### 5) 101<=Rollnumber<=125


**Task 1: Try the algo on Same Whether dataset - OneHotEncoding of features:and Train test Division 85%-15% and Gini Index as attribute selection measure**

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [47]:
#Predictor variables
Outlook = ['Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny', 'Sunny', 'Overcast',
            'Rainy', 'Rainy', 'Sunny', 'Rainy','Overcast', 'Overcast', 'Sunny']
Temperature = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool',
                'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
Humidity = ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal',
            'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High']
Wind = ['False', 'True', 'False', 'False', 'False', 'True', 'True',
            'False', 'False', 'False', 'True', 'True', 'False', 'True']

#Class Label:
Play = ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No',
'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']

In [48]:
dataset_list = list(zip(Outlook, Temperature, Humidity, Wind, Play))
dataset = pd.DataFrame(dataset_list, columns = ["Outlook", "Temperature", "Humidity", "Wind", "Play"])
print(dataset.shape)
dataset.head()

(14, 5)


Outlook Temperature Humidity   Wind Play
0     Rainy         Hot     High  False   No
1     Rainy         Hot     High   True   No
2  Overcast         Hot     High  False  Yes
3     Sunny        Mild     High  False  Yes
4     Sunny        Cool   Normal  False  Yes

In [49]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Outlook      14 non-null     object
 1   Temperature  14 non-null     object
 2   Humidity     14 non-null     object
 3   Wind         14 non-null     object
 4   Play         14 non-null     object
dtypes: object(5)
memory usage: 688.0+ bytes


In [50]:
print("Unique Outlook values: ", dataset['Outlook'].unique())

print("Unique Temperature values: ", dataset['Temperature'].unique())

print("Unique Humidity values: ", dataset['Humidity'].unique())

print("Unique Wind values: ", dataset['Wind'].unique())

print("Unique Play values (Class Label): ", dataset['Play'].unique())

Unique Outlook values:  ['Rainy' 'Overcast' 'Sunny']
Unique Temperature values:  ['Hot' 'Mild' 'Cool']
Unique Humidity values:  ['High' 'Normal']
Unique Wind values:  ['False' 'True']
Unique Play values (Class Label):  ['No' 'Yes']


In [51]:
dummy = pd.get_dummies(dataset.iloc[:,:-1])

cols = dataset.columns.tolist()
cols.remove("Play")

dataset = dataset.drop(cols, axis = 1)
dataset = pd.concat([dummy,dataset], axis = 1)

In [52]:
labels = dataset['Play']
labels

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Play, dtype: object

In [53]:
data_train, data_test, target_train, target_test = train_test_split(dataset.iloc[:,:-1], labels, test_size = 0.15, random_state = 108)

In [54]:
DT = DecisionTreeClassifier(max_leaf_nodes = 108, random_state = 108)

In [55]:
final_model = DT.fit(data_train,target_train)

In [56]:
target_predict = DT.predict(data_test)

In [57]:
target_predict

array(['Yes', 'No', 'Yes'], dtype=object)

In [58]:
target_test

12    Yes
13     No
8     Yes
Name: Play, dtype: object

In [59]:
Accuracy = accuracy_score(target_test, target_predict)
Accuracy

1.0

In [60]:
confusion_matrix = confusion_matrix(target_test, target_predict)
confusion_matrix

array([[1, 0],
       [0, 2]])

In [61]:
precision = precision_score(target_test, target_predict, average=None)
precision

array([1., 1.])

In [62]:
recall = recall_score(target_test, target_predict, average=None)
recall

array([1., 1.])

##### (1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

In [63]:
'''
Rainy = 0,1,0
Mild = 0,0,1
Normal = 0,1
False = 1,0
'''
q1 = [0,1,0,0,0,1,0,1,1,0]

##### (2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?

In [64]:
'''
Sunny = 0,0,1
Cool = 1,0,0
High = 1,0
True = 0,1
'''
q2 = [0,0,1,1,0,0,1,0,0,1]

features = dataset.columns.tolist()
features.remove("Play")
df = pd.DataFrame([q1,q2], columns = features)
df.head()

Outlook_Overcast  Outlook_Rainy  Outlook_Sunny  Temperature_Cool  \
0                 0              1              0                 0   
1                 0              0              1                 1   

   Temperature_Hot  Temperature_Mild  Humidity_High  Humidity_Normal  \
0                0                 1              0                1   
1                0                 0              1                0   

   Wind_False  Wind_True  
0           1          0  
1           0          1

In [65]:
ans = DT.predict(df)
print("Play predicted:\nq1: {}\nq2: {}".format(ans[0],ans[1]))

Play predicted:
q1: Yes
q2: No
