In [49]:
import numpy as np

## Training Data

In [50]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [51]:
# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print(weights)
print(biases)

[[0.14544877 0.4390103  0.25835721]
 [0.6306312  0.94404226 0.14858401]]
[[0.79254473 0.14323292]
 [0.19046435 0.17816994]
 [0.10598733 0.92188677]
 [0.05561651 0.29645006]
 [0.76336357 0.84731302]
 [0.68139182 0.19710236]
 [0.41822654 0.0598285 ]
 [0.49824056 0.25297827]
 [0.32849164 0.45982164]
 [0.96613746 0.04014367]
 [0.14025851 0.33107504]
 [0.94123872 0.44076107]
 [0.68265475 0.29301975]
 [0.9927745  0.8207609 ]
 [0.24198929 0.71370407]]


In [52]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [53]:
# Generate predictions
preds = model(inputs)

In [54]:
# Compare with targets
print("Predictions : ", preds)
print("Targets : ",targets)

Predictions :  [[ 51.93335511 115.81925398]
 [ 68.59407034 150.15070417]
 [ 86.57212861 190.90633596]
 [ 43.32805085 110.71225763]
 [ 71.02932226 145.38980301]
 [ 51.82220221 115.87312342]
 [ 68.82183253 150.03236273]
 [ 86.96438184 190.23742747]
 [ 43.60092598 110.87562921]
 [ 71.23209615 144.58263366]
 [ 51.28106889 116.00709611]
 [ 69.34484472 150.41329529]
 [ 87.14879603 190.27746895]
 [ 44.26520884 111.23656847]
 [ 70.50794798 145.25619405]]
Targets :  [[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


## Loss function

In [55]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [56]:
# Compute loss
loss = mse(preds, targets)
print(loss)

3335.0276586496957


## Compute Gradient

In [57]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print(weights_grad)
print(biases_grad)

[[-1681.81111616 -3119.80800383 -1704.92652443]
 [ 8867.71302719  8315.62531524  5206.82466879]]
[[-0.54221932  6.10923386]
 [-1.65412395  6.55342722]
 [-4.32371619  7.7208448 ]
 [ 2.84374011  9.82830102]
 [-4.26275703  3.5186404 ]
 [-0.55703971  6.11641646]
 [-1.62375566  6.53764836]
 [-4.27141575  7.631657  ]
 [ 2.88012346  9.85008389]
 [-4.23572051  3.41101782]
 [-0.62919081  6.13427948]
 [-1.5540207   6.58843937]
 [-4.2468272   7.63699586]
 [ 2.96869451  9.89820913]
 [-4.3322736   3.50082587]]


## Adjust weights

In [58]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [59]:
print(weights)
print(biases)

[[0.16226688 0.47020838 0.27540648]
 [0.54195407 0.860886   0.09651576]]
[[0.79255015 0.14317182]
 [0.19048089 0.17810441]
 [0.10603057 0.92180956]
 [0.05558807 0.29635178]
 [0.7634062  0.84727784]
 [0.68139739 0.19704119]
 [0.41824278 0.05976313]
 [0.49828328 0.25290195]
 [0.32846284 0.45972314]
 [0.96617982 0.04010956]
 [0.1402648  0.3310137 ]
 [0.94125426 0.44069518]
 [0.68269722 0.29294338]
 [0.99274482 0.82066191]
 [0.24203261 0.71366906]]


In [60]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

1769.5819662241488


In [61]:
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [62]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

49.884618119113235


In [63]:
# Print predictions
print(preds)

[[ 58.16835032  71.05053273]
 [ 80.46333633  96.28420929]
 [120.33357033 141.32539508]
 [ 24.15933448  41.85531162]
 [ 97.73908044 109.53604635]
 [ 58.05722719  71.10438773]
 [ 80.69103748  96.16589956]
 [120.72571846 140.65666583]
 [ 24.43213649  42.01863942]
 [ 97.94179999 108.72909329]
 [ 57.51623889  71.23832452]
 [ 81.21390952  96.54673005]
 [120.91008323 140.69669658]
 [ 25.09624135  42.37948196]
 [ 97.21784587 109.40247319]]


In [64]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
