### 5) 101<=Rollnumber<=125

**Task 1: Try the algo on Dataset3 - OneHotEncoding of features:and Train test Division 85%-15%**

In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [80]:
dataset = pd.read_csv("./PracticeDataSets/Dataset3.csv")
dataset

Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0

In [81]:
print("Unique Outlook values: ", dataset['Outlook'].unique())

Unique Outlook values:  ['R' 'O' 'S']


In [82]:
print("Unique Temperature values: ", dataset['Temp'].unique())

Unique Temperature values:  ['H' 'M' 'C']


In [83]:
print("Unique Humidity values: ", dataset['Humidity'].unique())

Unique Humidity values:  [1 2 0]


In [84]:
print("Unique Wind values: ", dataset['Wind'].unique())

Unique Wind values:  ['F' 'T']


In [85]:
print("Unique Class values(Class Label): ", dataset['Class'].unique())

Unique Class values(Class Label):  [0 1]


In [86]:
dummy = pd.get_dummies(dataset.iloc[:,:-1])

cols = dataset.columns.tolist()
cols.remove("Class")

dataset = dataset.drop(cols, axis = 1)
dataset = pd.concat([dummy,dataset], axis = 1)

In [87]:
dataset.head()

Humidity  Outlook_O  Outlook_R  Outlook_S  Temp_C  Temp_H  Temp_M  Wind_F  \
0         1          0          1          0       0       1       0       1   
1         2          0          1          0       0       1       0       0   
2         1          1          0          0       0       1       0       1   
3         1          0          1          0       0       0       1       1   
4         1          0          0          1       1       0       0       1   

   Wind_T  Class  
0       0      0  
1       1      0  
2       0      1  
3       0      1  
4       0      1

In [88]:
labels = dataset['Class']
labels

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    0
11    1
12    1
13    0
Name: Class, dtype: int64

In [89]:
data_train, data_test, target_train, target_test = train_test_split(dataset.iloc[:,:-1],labels, test_size = 0.15, random_state = 108)

In [90]:
# creating intsance
gnb = GaussianNB()

In [91]:
# fitting the model or training
gnb.fit(data_train, target_train)

GaussianNB()

In [92]:
# testing
target_predict = gnb.predict(data_test)
print(target_predict)

[0 1 0]


In [93]:
print(target_test)

12    1
13    0
8     1
Name: Class, dtype: int64


In [94]:
Accuracy = accuracy_score(target_test, target_predict)
print(Accuracy)

0.0


Bcoz,
target_test => 1 0 1
target_predict => 1 0 1

In [95]:
confusion_matrix = confusion_matrix(target_test, target_predict)
confusion_matrix

array([[0, 1],
       [2, 0]])

In [96]:
precision = precision_score(target_test, target_predict, average=None)
precision

array([0., 0.])

In [97]:
recall = recall_score(target_test, target_predict, average=None)
recall

array([0., 0.])